### PR TITLE
Add java support

### PR DESCRIPTION
**Pull request by urielsalis**

### CODE REVIEW

**Comment by rohitpaulk** [comment]
This should be done today! Ref: https://github.com/codecrafters-io/build-your-own-http-server/pull/17#issuecomment-1825664443

**Comment by rohitpaulk** [comment]
@urielsalis I pushed a couple of changes related to compiling templates, but looks like the starter code is failing tests:

Screenshot 2023-11-24 at 23 02 21

Could you try to get the tests working? You'll find instructions on how to execute them in the readme here: https://github.com/codecrafters-io/course-sdk

**Comment by rohitpaulk** [comment]
@urielsalis We're also working on a way to make course-sdk easier to use, which should be ready mid next-week. That should make the whole language support experience more user-friendly. 

I'll wait for that to land before looking at the other PRs, linking them here so that the github timeline links here: 

- https://github.com/codecrafters-io/build-your-own-sqlite/pull/52
- https://github.com/codecrafters-io/build-your-own-grep/pull/48
- https://github.com/codecrafters-io/build-your-own-http-server/pull/17
- https://github.com/codecrafters-io/build-your-own-git/pull/56
- https://github.com/codecrafters-io/build-your-own-git/pull/55
- https://github.com/codecrafters-io/build-your-own-redis/pull/107

**Comment by urielsalis** [comment]
@rohitpaulk I was missing the dest address. It should work now.

**Comment by urielsalis** [comment]
image
Works with course-sdk!

**Comment by urielsalis** [comment]
And I made sure to run the same in all the other PRs :D

**Comment by rohitpaulk** [comment]
@urielsalis awesome! Added the Java guide here: https://docs.codecrafters.io/challenges/language-support/java. Will quickly test this against the [new course-sdk](https://github.com/codecrafters-io/course-sdk-v2) we're working on and hoping to merge tomorrow!

**Comment by urielsalis** [comment]
Looks good!

Might be worth adding a link to Intellij Community edition (same as for Kotlin). Makes Java way more begginer friendly than the vscode plugins

**Comment by urielsalis** [comment]
> Will quickly test this against the [new course-sdk](https://github.com/codecrafters-io/course-sdk-v2) we're working on and hoping to merge tomorrow!

@rohitpaulk did this myself just now and all of them, including sqlite which didnt work with the previous sdk, seem to work!

**Pull request merged**
